# Generated by Django 5.2.3 on 2025-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
